// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVFkM5PpOfxb_q-MoHTatLwUpr9Jqo9eI',
    appId: '1:81358449961:android:6258bbc236fe6b51cd9b38',
    messagingSenderId: '81358449961',
    projectId: 'blue-6b5ab',
    databaseURL: 'https://blue-6b5ab-default-rtdb.firebaseio.com',
    storageBucket: 'blue-6b5ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL4t2emFzGpmG2YH2a9S3X0qkeEP6HRO8',
    appId: '1:81358449961:ios:d560b24eb46c7f54cd9b38',
    messagingSenderId: '81358449961',
    projectId: 'blue-6b5ab',
    databaseURL: 'https://blue-6b5ab-default-rtdb.firebaseio.com',
    storageBucket: 'blue-6b5ab.appspot.com',
    androidClientId: '81358449961-pmsacjllkgchpj8fjkr75pp3o873g43g.apps.googleusercontent.com',
    iosClientId: '81358449961-77grdnrp6pph71sq98hae2dvlr7ev360.apps.googleusercontent.com',
    iosBundleId: 'com.example.blueMobile',
  );
}
